;=====================================================================
;  GRAVASSIST - Boss Time theme, transcribed
;  GENERATED by tools/genboss.py - do not edit.
;
;  Four bars at 125 BPM = 7.68 seconds, three channels in step.
;  See the tool's header for what is transcribed and what is not.
;=====================================================================

; AY tone periods: period = 125000 / frequency.
boss_notes:
                dw  3822      ; C1
                dw  2273      ; A1
                dw  2145      ; A#1
                dw  2025      ; B1
                dw  1911      ; C2
                dw  1804      ; C#2
                dw  1517      ; E2
                dw  1351      ; F#2
                dw  1204      ; G#2
                dw   902      ; C#3
                dw   758      ; E3
                dw   451      ; C#4
                dw   379      ; E4
                dw   338      ; F#4
                dw   301      ; G#4
                dw   253      ; B4

BOSS_TRACKS     equ 3
; At or above this, a note index is percussion and the remainder
; is the AY noise period. The player MUST branch on it.
BOSS_NOISE      equ 200

; --- bass: 82 entries
boss_bass:
                db 6,13,21
                db 0,0,3
                db 5,13,10
                db 0,0,2
                db 4,13,21
                db 0,0,3
                db 6,13,10
                db 0,0,2
                db 5,13,10
                db 0,0,2
                db 4,13,10
                db 0,0,2
                db 11,13,10
                db 0,0,2
                db 7,13,10
                db 0,0,2
                db 6,13,21
                db 0,0,3
                db 9,13,21
                db 0,0,3
                db 6,13,42
                db 0,0,6
                db 5,13,10
                db 0,0,2
                db 4,13,10
                db 0,0,2
                db 6,13,10
                db 0,0,2
                db 5,13,10
                db 0,0,2
                db 3,13,10
                db 0,0,2
                db 4,13,10
                db 0,0,2
                db 8,13,10
                db 0,0,2
                db 2,13,10
                db 0,0,2
                db 7,13,10
                db 0,0,2
                db 4,13,21
                db 0,0,3
                db 6,13,42
                db 0,0,6
                db 5,13,10
                db 0,0,2
                db 4,13,21
                db 0,0,3
                db 6,13,10
                db 0,0,2
                db 5,13,10
                db 0,0,2
                db 4,13,10
                db 0,0,2
                db 11,13,10
                db 0,0,2
                db 7,13,10
                db 0,0,2
                db 6,13,21
                db 0,0,3
                db 9,13,10
                db 0,0,2
                db 10,13,10
                db 0,0,2
                db 6,13,53
                db 0,0,7
                db 4,13,10
                db 0,0,2
                db 6,13,10
                db 0,0,2
                db 5,13,10
                db 0,0,2
                db 4,13,21
                db 0,0,3
                db 8,13,10
                db 0,0,2
                db 7,13,21
                db 0,0,3
                db 4,13,21
                db 0,0,3
                db 6,13,42
                db 0,0,6
boss_bass_end:

; --- lead: 58 entries
boss_lead:
                db 12,10,42
                db 0,0,6
                db 16,10,10
                db 0,0,2
                db 12,10,21
                db 0,0,3
                db 16,10,10
                db 0,0,2
                db 13,10,21
                db 0,0,3
                db 12,10,21
                db 0,0,3
                db 15,10,10
                db 0,0,2
                db 12,10,63
                db 0,0,9
                db 16,10,10
                db 0,0,2
                db 12,10,32
                db 0,0,4
                db 16,10,10
                db 0,0,2
                db 14,10,10
                db 0,0,2
                db 13,10,21
                db 0,0,3
                db 16,10,21
                db 0,0,3
                db 12,10,63
                db 0,0,9
                db 16,10,10
                db 0,0,2
                db 12,10,21
                db 0,0,3
                db 16,10,10
                db 0,0,2
                db 13,10,21
                db 0,0,3
                db 12,10,21
                db 0,0,3
                db 15,10,10
                db 0,0,2
                db 12,10,63
                db 0,0,9
                db 16,10,10
                db 0,0,2
                db 12,10,21
                db 0,0,3
                db 16,10,10
                db 0,0,2
                db 14,10,21
                db 0,0,3
                db 13,10,21
                db 0,0,3
                db 16,10,21
                db 0,0,3
                db 12,10,42
                db 0,0,6
boss_lead_end:

; --- drums: 58 entries
boss_drums:
                db 1,13,3
                db 0,0,33
                db 1,8,3
                db 0,0,9
                db 206,12,3
                db 0,0,45
                db 1,13,3
                db 0,0,33
                db 1,8,3
                db 0,0,9
                db 206,12,3
                db 0,0,45
                db 1,13,3
                db 0,0,33
                db 1,8,3
                db 0,0,9
                db 206,12,3
                db 0,0,45
                db 1,13,3
                db 0,0,33
                db 1,8,3
                db 0,0,9
                db 206,12,3
                db 0,0,21
                db 1,8,3
                db 0,0,21
                db 1,13,3
                db 0,0,33
                db 1,8,3
                db 0,0,9
                db 206,12,3
                db 0,0,45
                db 1,13,3
                db 0,0,33
                db 1,8,3
                db 0,0,9
                db 206,12,3
                db 0,0,45
                db 1,13,3
                db 0,0,33
                db 1,8,3
                db 0,0,9
                db 206,12,3
                db 0,0,33
                db 1,8,3
                db 0,0,9
                db 1,13,3
                db 0,0,21
                db 1,8,3
                db 0,0,9
                db 1,8,3
                db 0,0,9
                db 206,12,3
                db 0,0,21
                db 206,12,3
                db 0,0,9
                db 206,12,3
                db 0,0,9
boss_drums_end:

; Where each track sits and how long it is. The player streams
; them out of the bank, so it needs both.
boss_tab:
                dw boss_bass, boss_bass_end-boss_bass
                dw boss_lead, boss_lead_end-boss_lead
                dw boss_drums, boss_drums_end-boss_drums

