;=====================================================================
;  GRAVASSIST - the tune's note table and its shape in the bank
;  GENERATED by tools/genboss.py - do not edit.
;
;  The notes themselves are NOT here: they are in build/TUNEnn.BIN
;  on the disc, loaded into RAM bank block 7 at boot.
;  Only what the player needs on every single note lives in main
;  memory, because main memory is what there is none of.
;=====================================================================

TUNE_BARS       equ 32
TUNE_NCOUNT     equ 20
TUNE_NOISE      equ 200      ; index >= this is percussion
TUNE_BYTES      equ 4542
TUNE_CHUNK      equ 1536
TUNE_CHUNKS     equ 3

; Offset and length of each track inside the blob, which the boot
; code lays down at the start of the block.
TUNE_BASS_OFF equ 0
TUNE_BASS_LEN equ 1812
TUNE_LEAD_OFF equ 1812
TUNE_LEAD_LEN equ 1242
TUNE_DRUMS_OFF equ 3054
TUNE_DRUMS_LEN equ 1488

; AY tone periods: period = 125000 / frequency.
tune_notes:
                dw  3822      ; C1
                dw  2408      ; G#1
                dw  2273      ; A1
                dw  2145      ; A#1
                dw  2025      ; B1
                dw  1911      ; C2
                dw  1804      ; C#2
                dw  1607      ; D#2
                dw  1517      ; E2
                dw  1351      ; F#2
                dw  1204      ; G#2
                dw   902      ; C#3
                dw   758      ; E3
                dw   451      ; C#4
                dw   402      ; D#4
                dw   379      ; E4
                dw   338      ; F#4
                dw   301      ; G#4
                dw   253      ; B4
                dw   225      ; C#5

